### ISSUE TITLE
Add pccommon to deployment

### ISSUE THREAD

**Issue by toxick** [rcbops/rpc-extras#10]
Please add pccommon.sh to the utility and neutron_agents containers.

  https://github.com/rsoprivatecloud/pubscripts/blob/master/pccommon.sh

There.

**Comment by andymcc** [comment]
@toxick I added a PR for this - can you confirm that works for you? I.e. is having it in /root acceptable or would you prefer it gets placed somewhere else? I set the perms to 0700.

**Comment by toxick** [comment]
Hi andy - thanks for that.  Looks like that should work just fine.

**Comment by andymcc** [comment]
This merged - forgot to close the issue!

**Comment by b3rnard0** [comment]
@andymcc My KPIs have suffered greatly.... :-)
