### ISSUE TITLE
openjdk-7-jre installation into multiple containers adds ~20mins to deployment time

### ISSUE THREAD

**Issue by b3rnard0** [rcbops/rpc-extras#19]
Opened by odyssey4me on 2014-11-27 12:17:37+00:00 at https://github.com/rcbops/ansible-lxc-rpc/issues/660

------------------------------------------------------------

openjdk-7-jre is installed into the elasticsearch, kibana, logstash and utility containers - for each installation it takes approximately 4 minutes. A potential optimisation to reduce deployment time would be to include this package in a pre-installed image which is used to create these containers.

**Comment by odyssey4me** [comment]
`openjdk-7-jre` has been changed for `openjdk-7-jre-headless` which reduces the footprint a little, and the jre is only installed in the elasticsearch and logstash containers which are the only two locations where it's needed.
