### ISSUE TITLE
Dynamic inventory assumes /opt/os-ansible-deployment

### ISSUE THREAD

**Issue by mattt416** [rcbops/rpc-extras#33]
Despite there being an override for `rpc_repo_path` in `etc/openstack_deploy/user_extras_variables.yml`, this is never read as dynamic_inventory.py pulls `rpc_repo_path` from `playbooks/group_vars/all.yml`.  This means the user cannot relocate os-ansible-deployment without having to modify rpc-extras itself.

Something like this will help, but then puts an assumption on `/etc/openstack_deployment`:

```
#!/usr/bin/env python
import os
import sys
import subprocess
import yaml

basedir = os.path.abspath(os.path.dirname(__file__))
group_vars_yaml = os.path.join(basedir, '../group_vars/all.yml')
user_vars_yaml = '/etc/openstack_deploy/user_extras_variables.yml'

try:
    rpc_repo_path = yaml.load(open(user_vars_yaml, 'r'))['rpc_repo_path']
except KeyError:
    rpc_repo_path = yaml.load(open(group_vars_yaml, 'r'))['rpc_repo_path']

rpc_inventory = os.path.join(rpc_repo_path,
                             'playbooks/inventory/dynamic_inventory.py')
subprocess.call([rpc_inventory] + sys.argv[1:])
```

Anyone have any suggestions as to how we should approach this?

**Comment by miguelgrinberg** [comment]
Per our discussion, I'm going to change this script to look for the `rpc_repo_path ` variable in the following locations:

- /etc/openstack_deploy/
- $HOME/openstack_deploy/
- $(pwd)/openstack_deploy/
- rpc_extras/playbooks/group_vars/all.yml
