### ISSUE TITLE
F5 Pool Monitoring

### ISSUE THREAD

**Issue by Apsu** [rcbops/rpc-extras#46]
XML is deprecated in Juno Keystone, and will be removed in Kilo. The F5 currently uses the xml output to grab the token and monitor the nodes in the various api pools.

The python on the F5 is 2.4 and read only, with no json support. We will have to devise an alternative for the Kilo release.

**Comment by b3rnard0** [comment]
This is currently in our backlog we just need to determine priority and when: 

https://trello.com/c/Qtb70ERo/583-f5-pool-monitoring-in-kilo

@Apsu @claco @mancdaz

**Comment by b3rnard0** [comment]
Closed in #54 .
