### ISSUE TITLE
Rabbitmq health alarms

### ISSUE THREAD

**Issue by paul5801** [rcbops/rpc-extras#47]
It appears that we are not monitoring anything in regards to rabbitmq's status.  The rabbitmq_status.py seems to do the appropriate checks for cluster status, channels >1, cluster size etc...  However, I do not see any alarms created in monitoring.rackspace.net that pertain to the health of the rabbit cluster.  I see only 2 alarms for disk_free and memory.  Are we not monitoring anything of importance in regards to rabbit's health?

**Comment by BjoernT** [comment]
As discussed the rabbitmq check does more checks and the monitoring will also generate an alarm if the return code is > 0. Currently we do generate a generic alarm under the following circumstances:
* >1 channel per connection
* can't make api queries to /nodes or /overview
* Cluster size smaller than expected
* Not member of a cluster

The 2 additional alarms are related to metrics not the check by itself. Do you see a need for additional checks ?

**Comment by b3rnard0** [comment]
Per @BjoernT at bug triage today:

bjoern:	 I think we have enough checks already and the issue was based on wrong assumptions
