### ISSUE TITLE
rpc_f5_config.sh is not generating a VIP for port 8181 (pip repo)

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-extras#91]
rpc_f5_config.sh is not generating a VIP for port 8181 for the repo container. That needs to be addressed asap.

**Comment by miguelgrinberg** [comment]
I think this is covered by the changes in #89, we have port 8181 there.

**Comment by b3rnard0** [comment]
Calling this a duplicate of #89 , which is currently being reviewed.
