### ISSUE TITLE
Add support for critical fileystems thresholds

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-extras#94]
Currently we do only create warning alarms which do not trigger core.
I added configurable warning and critical thresholds. Critical thresholds will also set off core.
Additionally we are working in getting warnings into core as well for our devices

**Comment by claco** [comment]
@b3rnard0 @BjoernT Going to bump this to 10.1.7. Because the backport needs to be worked back into OSAD and rpc-maas repos for Juno, this is going to take a bit longer.

**Comment by BjoernT** [comment]
@claco That's ok

**Comment by BjoernT** [comment]
Juno will be tracked at https://bugs.launchpad.net/openstack-ansible/+bug/1455999 since it still belongs to osad. I guess we can remove the juno-backport-potential tag
